// ─── SettingsView ─────────────────────────────────────────────────────────
import React, { useState, useEffect } from 'react'
import { C } from '../constants/theme'
import { storage } from '../utils/storage'
import { getPushStatus, subscribeToPush, unsubscribeFromPush } from '../utils/pushNotifications'
import { AuthSection } from '../components/AuthSection'

export function SettingsView({
  tasks, userName, setUserName, userEmail, setUserEmail, onClearAll,
  user, onSignIn, onSignOut, syncing,
}) {
  const [pushEnabled, setPushEnabled] = useState(false)
  const [pushStatus, setPushStatus] = useState('default')
  const [pushLoading, setPushLoading] = useState(false)

  useEffect(() => {
    const status = getPushStatus()
    setPushStatus(status)
    setPushEnabled(status === 'granted')
  }, [])

  const handleTogglePush = async () => {
    setPushLoading(true)
    try {
      if (pushEnabled) {
        await unsubscribeFromPush()
        setPushEnabled(false)
        setPushStatus('default')
      } else {
        const sub = await subscribeToPush()
        if (sub) {
          setPushEnabled(true)
          setPushStatus('granted')
        } else {
          setPushStatus(getPushStatus())
        }
      }
    } finally {
      setPushLoading(false)
    }
  }

  const inp = {
    background: C.surface, border: `1px solid ${C.border}`, borderRadius: 10,
    padding: '8px 12px', color: C.text, fontFamily: 'inherit', fontSize: 14,
    outline: 'none', width: '100%', boxSizing: 'border-box',
  }

  return (
    <div>
      {/* ── Cloud Sync / Auth ─────────────────────────────────────────── */}
      <AuthSection user={user} onSignIn={onSignIn} onSignOut={onSignOut} syncing={syncing} />

      {/* profile */}
      <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 18, padding: 20, marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: C.accent, marginBottom: 14, textTransform: 'uppercase', letterSpacing: 1 }}>Profile</div>
        <label style={{ fontSize: 12, color: C.muted, display: 'block', marginBottom: 5 }}>Your Name</label>
        <input value={userName} onChange={e => setUserName(e.target.value)}
          onBlur={() => storage.setName(userName)}
          placeholder="Enter your name" style={{ ...inp, marginBottom: 14 }} />
        <label style={{ fontSize: 12, color: C.muted, display: 'block', marginBottom: 5 }}>Email Address</label>
        <input value={userEmail} onChange={e => setUserEmail(e.target.value)}
          onBlur={() => storage.setEmail(userEmail)}
          type="email" placeholder="you@example.com" style={inp} />
      </div>

      {/* push reminders */}
      <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 18, padding: 20, marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: C.accent, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 }}>Push Reminders</div>
        <div style={{ fontSize: 13, color: C.muted, lineHeight: 1.7, marginBottom: 14 }}>
          Get a daily 9 AM reminder with your task summary. Requires backend running on port 3000.
        </div>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span style={{ fontSize: 14, color: C.text }}>Enable Reminders</span>

          {pushStatus === 'unsupported' ? (
            <span style={{ fontSize: 12, color: C.muted }}>Not supported in this browser</span>
          ) : pushStatus === 'denied' ? (
            <span style={{ fontSize: 12, color: C.danger }}>Blocked — reset in browser settings</span>
          ) : (
            <button
              onClick={handleTogglePush}
              disabled={pushLoading}
              style={{
                width: 48, height: 26, borderRadius: 13, border: 'none', cursor: 'pointer',
                background: pushEnabled ? C.accent : C.surface,
                position: 'relative', transition: 'background .2s',
                opacity: pushLoading ? 0.5 : 1,
              }}
            >
              <span style={{
                width: 20, height: 20, borderRadius: '50%',
                background: '#fff', position: 'absolute', top: 3,
                left: pushEnabled ? 25 : 3, transition: 'left .2s',
              }} />
            </button>
          )}
        </div>
      </div>

      {/* email reports */}
      <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 18, padding: 20, marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: C.accent, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 }}>Email Reports</div>
        <div style={{ fontSize: 13, color: C.muted, lineHeight: 1.7, marginBottom: 14 }}>
          Automated weekly & monthly reports generated by the backend. Ensure the backend server is running on port 3000.
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button onClick={async () => {
            if (!userEmail) return alert('Please enter your email address first.');
            try {
              const res = await fetch('http://localhost:3000/api/report/weekly', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ email: userEmail, userName, tasks })
              });
              if (res.ok) alert('Weekly report sent successfully!');
              else alert('Failed to send report. Is the backend running?');
            } catch (err) { alert('Network error. Ensure backend is running.'); }
          }} style={{
            flex: 1, padding: '10px 6px', borderRadius: 10,
            background: C.surface, border: `1px solid ${C.purple}`,
            color: C.text, fontFamily: 'inherit', fontSize: 12, cursor: 'pointer',
          }}>
            Send Weekly Report
          </button>
          
          <button onClick={async () => {
            if (!userEmail) return alert('Please enter your email address first.');
            try {
              const res = await fetch('http://localhost:3000/api/report/monthly', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ email: userEmail, userName, tasks })
              });
              if (res.ok) alert('Monthly report sent successfully!');
              else alert('Failed to send report. Is the backend running?');
            } catch (err) { alert('Network error. Ensure backend is running.'); }
          }} style={{
            flex: 1, padding: '10px 6px', borderRadius: 10,
            background: C.surface, border: `1px solid ${C.purple}`,
            color: C.text, fontFamily: 'inherit', fontSize: 12, cursor: 'pointer',
          }}>
            Send Monthly Report
          </button>
        </div>
      </div>

      {/* danger zone */}
      <div style={{ background: C.card, border: `1px solid ${C.danger}44`, borderRadius: 18, padding: 20 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: C.danger, marginBottom: 10, textTransform: 'uppercase', letterSpacing: 1 }}>Danger Zone</div>
        <button onClick={() => { if (window.confirm('Delete ALL tasks? Cannot be undone.')) onClearAll() }}
          style={{
            width: '100%', padding: 10, borderRadius: 10,
            background: 'transparent', border: `1px solid ${C.danger}`,
            color: C.danger, fontFamily: 'inherit', fontSize: 13, cursor: 'pointer',
          }}>
          Clear All Tasks
        </button>
      </div>
    </div>
  )
}
